[package]
name = "Command Menu"
description = "A mod testing utility."
homepage = "https://www.nexusmods.com/morrowind/mods/55193"
repository = "https://github.com/C3pa/Morrowind-Command-Menu"
authors = [ "C3pa" ]
version = "2.2.0"

[dependencies.mwse]
buildnumber = 4520

[dependencies.mge-xe]
version = ">=0.18.0"

[tools.mwse]
lua-mod = "Command Menu"
